feat: 🎸 testing owasp zap

diff --git a/.github/workflows/deploy-preview.yml b/.github/workflows/deploy-preview.yml
--- a/.github/workflows/deploy-preview.yml
+++ b/.github/workflows/deploy-preview.yml
@@ -7,13 +7,14 @@ env:
 
 on:
   push:
-    branches-ignore: [ main ]
+    branches: [ preview ]
   pull_request:
-    branches-ignore: [ main ]
+    branches: [ preview ]
       
 jobs:
   security:
     runs-on: ubuntu-latest
+    name: Scan securiry dependencies con SNYK
     steps:
       - uses: actions/checkout@v4
       - name: Run Snyk to check for vulnerabilities
@@ -23,6 +24,7 @@ jobs:
 
   test:
     runs-on: ubuntu-latest
+    name: Unit Test
     steps: 
       - uses: actions/checkout@v4
       - uses: actions/setup-node@v4
@@ -30,6 +32,50 @@ jobs:
           node-version: 20
       - run: npm ci --force
       - run: npm run test
+
+  zap_scan:
+    runs-on: ubuntu-latest
+    name: Scan the Next.js application
+    steps:
+      - uses: actions/checkout@v4
+      
+      - name: Use Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: '20'
+      
+      - name: Install dependencies
+        run: npm ci --force
+      
+      - name: Build Next.js app
+        run: npm run build
+      
+      - name: Start Next.js app
+        run: npm run start & npx wait-on http://localhost:3000
+      
+      - name: ZAP Scan
+        uses: zaproxy/action-baseline@v0.7.0
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          target: 'http://localhost:3000'
+          rules_file_name: '.zap/rules.tsv'
+          cmd_options: '-a'
+      
+      - name: Stop Next.js app
+        if: always()
+        run: kill $(lsof -t -i:3000) || true
+      
+      - name: Upload ZAP report
+        uses: actions/upload-artifact@v2
+        with:
+          name: ZAP Report
+          path: report.html
+      
+      - name: Fail on high alerts
+        if: failure()
+        run: |
+          echo "ZAP scan failed due to high alerts"
+          exit 1
 
   deploy:
     runs-on: ubuntu-latest
